// Generated by gencpp from file beamform/InterfTheta.msg
// DO NOT EDIT!


#ifndef BEAMFORM_MESSAGE_INTERFTHETA_H
#define BEAMFORM_MESSAGE_INTERFTHETA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beamform
{
template <class ContainerAllocator>
struct InterfTheta_
{
  typedef InterfTheta_<ContainerAllocator> Type;

  InterfTheta_()
    : id(0)
    , angle(0.0)  {
    }
  InterfTheta_(const ContainerAllocator& _alloc)
    : id(0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef uint16_t _id_type;
  _id_type id;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::beamform::InterfTheta_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beamform::InterfTheta_<ContainerAllocator> const> ConstPtr;

}; // struct InterfTheta_

typedef ::beamform::InterfTheta_<std::allocator<void> > InterfTheta;

typedef boost::shared_ptr< ::beamform::InterfTheta > InterfThetaPtr;
typedef boost::shared_ptr< ::beamform::InterfTheta const> InterfThetaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beamform::InterfTheta_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beamform::InterfTheta_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beamform::InterfTheta_<ContainerAllocator1> & lhs, const ::beamform::InterfTheta_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beamform::InterfTheta_<ContainerAllocator1> & lhs, const ::beamform::InterfTheta_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beamform

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beamform::InterfTheta_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beamform::InterfTheta_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beamform::InterfTheta_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beamform::InterfTheta_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beamform::InterfTheta_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beamform::InterfTheta_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beamform::InterfTheta_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75b733ac85d023a2ec3fae9ccef4c89e";
  }

  static const char* value(const ::beamform::InterfTheta_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75b733ac85d023a2ULL;
  static const uint64_t static_value2 = 0xec3fae9ccef4c89eULL;
};

template<class ContainerAllocator>
struct DataType< ::beamform::InterfTheta_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beamform/InterfTheta";
  }

  static const char* value(const ::beamform::InterfTheta_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beamform::InterfTheta_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16  id\n"
"float32 angle\n"
"\n"
;
  }

  static const char* value(const ::beamform::InterfTheta_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beamform::InterfTheta_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InterfTheta_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beamform::InterfTheta_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beamform::InterfTheta_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.id);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEAMFORM_MESSAGE_INTERFTHETA_H
