// Generated by gencpp from file jack_msgs/JackAudio.msg
// DO NOT EDIT!


#ifndef JACK_MSGS_MESSAGE_JACKAUDIO_H
#define JACK_MSGS_MESSAGE_JACKAUDIO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace jack_msgs
{
template <class ContainerAllocator>
struct JackAudio_
{
  typedef JackAudio_<ContainerAllocator> Type;

  JackAudio_()
    : data()
    , size(0)
    , header()  {
    }
  JackAudio_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , size(0)
    , header(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  _data_type data;

   typedef uint16_t _size_type;
  _size_type size;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;





  typedef boost::shared_ptr< ::jack_msgs::JackAudio_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jack_msgs::JackAudio_<ContainerAllocator> const> ConstPtr;

}; // struct JackAudio_

typedef ::jack_msgs::JackAudio_<std::allocator<void> > JackAudio;

typedef boost::shared_ptr< ::jack_msgs::JackAudio > JackAudioPtr;
typedef boost::shared_ptr< ::jack_msgs::JackAudio const> JackAudioConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jack_msgs::JackAudio_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jack_msgs::JackAudio_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jack_msgs::JackAudio_<ContainerAllocator1> & lhs, const ::jack_msgs::JackAudio_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.size == rhs.size &&
    lhs.header == rhs.header;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jack_msgs::JackAudio_<ContainerAllocator1> & lhs, const ::jack_msgs::JackAudio_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jack_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jack_msgs::JackAudio_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jack_msgs::JackAudio_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jack_msgs::JackAudio_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jack_msgs::JackAudio_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jack_msgs::JackAudio_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jack_msgs::JackAudio_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jack_msgs::JackAudio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e9da74397c8b7c277f8bbd8fe28001b";
  }

  static const char* value(const ::jack_msgs::JackAudio_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e9da74397c8b7c2ULL;
  static const uint64_t static_value2 = 0x77f8bbd8fe28001bULL;
};

template<class ContainerAllocator>
struct DataType< ::jack_msgs::JackAudio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jack_msgs/JackAudio";
  }

  static const char* value(const ::jack_msgs::JackAudio_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jack_msgs::JackAudio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] data\n"
"uint16    size\n"
"Header    header\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::jack_msgs::JackAudio_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jack_msgs::JackAudio_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.size);
      stream.next(m.header);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JackAudio_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jack_msgs::JackAudio_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jack_msgs::JackAudio_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "size: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.size);
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JACK_MSGS_MESSAGE_JACKAUDIO_H
